package com.danielealbano.androidremotecontrolmcp.geo

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import java.net.InetAddress
import java.nio.ByteBuffer

@DisplayName("LocationDb")
class LocationDbTest {
    // Fixture is generated by scripts/location-db (the format source of truth); see that module.
    // Ranges: 1.0.0.0/24 -> AU/Brisbane, 1.0.8.0..1.0.15.255 -> CN/Guangzhou, 200.1.2.0/24 -> US/Denver,
    // 2001:db8::/32 -> DE/Berlin.
    private val db: LocationDb by lazy {
        val bytes =
            requireNotNull(javaClass.getResourceAsStream("/geo/location-db-fixture.bin")) {
                "missing test fixture"
            }.readBytes()
        LocationDb(ByteBuffer.wrap(bytes))
    }

    private fun lookup(ip: String): GeoLocation? = db.lookup(InetAddress.getByName(ip))

    @Test
    @DisplayName("resolves IPv4 addresses to country and city")
    fun ipv4() {
        assertEquals(GeoLocation("AU", "Brisbane"), lookup("1.0.0.5"))
        assertEquals(GeoLocation("AU", "Brisbane"), lookup("1.0.0.255"))
        assertEquals(GeoLocation("CN", "Guangzhou"), lookup("1.0.10.0"))
        // 200.x.x.x has the high bit set: a signed read would misorder the binary search.
        assertEquals(GeoLocation("US", "Denver"), lookup("200.1.2.5"))
    }

    @Test
    @DisplayName("resolves IPv6 addresses to country and city")
    fun ipv6() {
        assertEquals(GeoLocation("DE", "Berlin"), lookup("2001:db8::1"))
        assertEquals(GeoLocation("DE", "Berlin"), lookup("2001:db8:ffff::abcd"))
    }

    @Test
    @DisplayName("returns null for gaps and out-of-range addresses")
    fun unknown() {
        assertNull(lookup("1.0.4.0")) // gap between the two IPv4 ranges
        assertNull(lookup("0.255.255.255")) // below the first range
        assertNull(lookup("2002::1")) // outside the IPv6 range
    }
}
